name: build
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: 0 2 * * *
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/fedora:rawhide
      # Fix SELinux for the built OSTree: https://github.com/coreos/rpm-ostree/issues/1943
      options: --privileged --security-opt label:disable
    steps:
      - name: Install dependencies
        run: dnf install -y rpm-ostree selinux-policy selinux-policy-targeted policycoreutils podman

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Login
        run: podman login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Image Metadata
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: |
            vauxite
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/ublue-os/vauxite/main/README.md

      - name: Build label flags
        id: fmt
        run: |
          LABELS=$(cat << EOF
          ${{ steps.meta.outputs.labels }}
          EOF
          )
          IFS=$'\n'
          OUTPUT=$(for l in $LABELS; do echo -n "-l \"$l\" "; done)
          echo "::set-output name=labels::$OUTPUT"

      - name: Build OSTree container image and push to registry
        uses: Wandalen/wretry.action@master
        with:
          command: rpm-ostree compose image --initialize --format=registry ${{ steps.fmt.outputs.labels }} fedora-vauxite.yaml ghcr.io/ublue-os/vauxite:latest
          attempt_limit: 3
          attempt_delay: 2000
